version: "3.9"

networks:
    nginx-php81-node:
    
services:
 nginx-service:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx-container
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - php81-service
      - database
    networks:
      - nginx-php81-node
 php81-service:
  build:
    context: .
    dockerfile: ./php/Dockerfile
  container_name: php81-container
  ports:
    - 9000:9000
  volumes:
    - ./public:/usr/share/nginx/html
  networks:
    - nginx-php81-node
 node-service:
  image: node:latest
  container_name: node-container
  volumes:
    - ./public:/usr/share/nginx/html
  working_dir: /usr/share/nginx/html
  networks:
    - nginx-php81-node
 database:
  networks:
    - nginx-php81-node
  image: postgres:${POSTGRES_VERSION:-13}-alpine
  environment:
    POSTGRES_DB: ${POSTGRES_DB:-app}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
    POSTGRES_USER: ${POSTGRES_USER:-symfony}
  volumes:
    - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data: null
